### ISSUE TITLE
CUDA out of memory after a few epochs

### ISSUE THREAD

**Issue by jonilaserson** [omerbt/Splice#133]
Trying your code in Colab, everything goes well for a few minutes (~300 epochs) and then it gets a CUDA memory error. Is there a leak somewhere?
https://colab.research.google.com/drive/17UgzBmKtqRXniuG6fHqMGh3xIaVIJnd2?usp=sharing

```
Traceback (most recent call last):
  File "train.py", line 87, in <module>
    train_model(dataroot)
  File "train.py", line 58, in train_model
    losses = criterion(outputs, inputs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/Splice/util/losses.py", line 64, in forward
    losses['loss_global_cls'] = self.calculate_crop_cls_loss(outputs['x_global'], inputs['B_global'])
  File "/content/Splice/util/losses.py", line 90, in calculate_crop_cls_loss
    cls_token = self.extractor.get_feature_from_input(a)[-1][0, 0, :]
  File "/content/Splice/models/extractor.py", line 84, in get_feature_from_input
    self.model(input_img)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/.cache/torch/hub/facebookresearch_dino_main/vision_transformer.py", line 212, in forward
    x = blk(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/root/.cache/torch/hub/facebookresearch_dino_main/vision_transformer.py", line 108, in forward
    y, attn = self.attn(self.norm1(x))
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/root/.cache/torch/hub/facebookresearch_dino_main/vision_transformer.py", line 85, in forward
    attn = (q @ k.transpose(-2, -1)) * self.scale
RuntimeError: CUDA out of memory. Tried to allocate 30.00 MiB (GPU 0; 11.17 GiB total capacity; 10.35 GiB already allocated; 23.81 MiB free; 10.68 GiB reserved in total by PyTorch)
```

**Comment by RafailFridman** [comment]
I got a Tesla T4 with 15G of memory in colab and it worked fine.
You can try restarting your runtime until you get a better GPU.

**Comment by tnarek** [comment]
Hi, we noticed that sometimes, depending on the GPU allocated, there is Cuda out of memory issues when running in Colab. As @RafailFridman mentioned, you can try resetting the runtime until you get more GPU memory, or you can try working with lower res images (can be controlled using the A_resize, B_resize configuration parameters).
By the way, that we've also released a [Colab notebook](https://colab.research.google.com/github/omerbt/Splice/blob/master/Splice.ipynb).
